"""
Property-based testing of the axioms with `Hypothesis
<https://hypothesis.readthedocs.io>`_: an :class:`Axiom` is stated once
on an abstract base class of :mod:`discopy.abc` as a sequent — see
:mod:`discopy.pattern` for the language and :mod:`discopy.search` for
the rules — a category generates its own objects and arrows through
:meth:`Testable.strategy` — by the rules of :mod:`discopy.search` for
diagrams — and the matrix in ``proptest/`` searches every cell for a
counterexample.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Equation
    Axiom
    AxiomFailure
    Testable
    Serialisable
    Relabelling

.. admonition:: Functions

    .. autosummary::
        :template: function.rst
        :nosignatures:
        :toctree:

        axiom
        assert_axioms

How to develop DisCoPy against its property suite: state the laws before
writing the implementation, let the matrix search for counterexamples,
replay a failure deterministically, record the counterexample so the bug
can never come back unnoticed, and audit the search strategy whenever a
bug escapes it.

The suite
---------

- ``proptest/test_axioms.py`` is the matrix: every :class:`Axiom` of
  every enrolled category, one pytest cell per pair, its equations
  generated by :meth:`Axiom.strategy`: the arguments sampled from the
  patterns of the sequent the law's own signature states, and the law
  evaluated on them.
- :class:`Serialisable` states the laws of any type that generates its
  own instances, whatever its level: :meth:`Serialisable.repr_transparency`,
  :meth:`Serialisable.pickling`, :meth:`Serialisable.copying` and
  :meth:`Serialisable.serialisation` are cells of the matrix for every
  enrolled type, which read back in :meth:`Serialisable.environment`:
  the package's public names and its own module's, so that a
  representation printing bare names evaluates without the category
  declaring anything.
- ``proptest/test_counterexamples.py`` replays every recorded
  counterexample deterministically — no generation, no search: the
  matrix's explicit phase. Its memory is Hypothesis's example database,
  ``.hypothesis`` on your machine and a workflow artifact on CI, which
  every run reads before it searches.
- Select cells with pytest's own ``-k``: ``uv run pytest proptest/ -k
  'Arrow and unitality' -vrsxX``. Recorded counterexamples carry the id
  of their matrix cell, so one expression selects a law's search and its
  records together.
- :func:`assert_axioms` dry-runs every axiom of a category on one
  example, the fast loop before the full matrix.

Properties before implementation
--------------------------------

A feature starts as mathematics, and the mathematics starts as
properties. Before implementing anything, write the laws down:

1. **State the laws.** Which equations define the new structure? Which
   level of :mod:`discopy.abc` do they belong to? Which existing axioms
   must the new category inherit, compare :meth:`Axiom.modulo` a
   quotient, declare :meth:`Axiom.inapplicable` — or :meth:`Axiom.weaken`
   to the subspace a strategy parameter cuts out, so that a
   :meth:`Axiom.failing` law with a green subspace shows one expected
   failure and one green cell? Write this down before any implementation,
   as a sequent: the variables and their sorts, the premises and their
   types.
2. **Scaffold the axioms.** Declare each law as an :func:`axiom` on the
   abstract base class — or an ad-hoc property in its ``proptest/`` file
   when it is a boolean rather than an equation — and enrol the category
   by implementing :meth:`Testable.strategy`. The body calls the
   operations the feature will provide; until they exist, the cell fails.
   That is the red state of the loop.
3. **Reach the structure.** Declare the new structure as a
   :func:`discopy.search.rule` on the abstract base class, so that the
   search builds terms containing it, and check the reach with a
   :func:`hypothesis.find`: a green cell whose strategy never generates
   the structure proves nothing.
4. **Implement until green**, on the dry run first, then the matrix.

A property is meaningful when it quantifies over all terms of a category.
Single behaviours — validation raises, error messages, encoding pins —
stay as unit tests in ``test/``.

Debugging a failing cell
------------------------

1. **Isolate it**: ``uv run pytest proptest/ -k '<Category> and <law>'
   -x -vrsxX``. Hypothesis reports the shrunk falsifying example as
   labelled samples; on rerun the ``.hypothesis`` database replays it
   first, so the failure is stable on your machine. A failure CI found is
   in the artifact its run uploaded: the ``shared`` profile reads that
   database too, given a ``GITHUB_TOKEN``, and the cell fails for you the
   same way without a search.
2. **Record it, then debug.** DisCoPy is transparent, so the printed
   samples are valid Python building the exact counterexample. Paste them
   into a record in ``proptest/test_counterexamples.py`` (format below)
   before touching the implementation: the database remembers a failure
   only under the Hypothesis ``uv.lock`` pins and only while an artifact
   lives, while a record reproduces it on every machine, from a CI log
   included, and stays as the pin once the bug is fixed.
3. **Debug against the record**, not the search. In a REPL, call the
   record's axiom on its arguments and inspect the returned
   :class:`Equation`'s sides. Do not reach for :meth:`Axiom.falsify` to
   reproduce a known failure: it searches and shrinks afresh each run and
   may land on a different counterexample, or none. It remains only for
   interactive exploration when no failure is in hand.
4. **Fix the root cause.** The recorded cell flips green and stays as the
   regression pin; there is nothing else to write.
5. **Or file it.** If the fix is out of scope, open an issue, declare the
   axiom ``.failing("<reason> (#<issue>)")`` where the category breaks it,
   and keep the record: it xfails together with the axiom, strictly, so
   the day the bug is fixed the record fails as an unexpected pass until
   the :meth:`Axiom.failing` declaration is removed — at which point the
   record is the pin. The search cell xfails too, without strictness:
   whether a search finds a rare counterexample within its budget is not
   a fact about the law.

A counterexample against an ad-hoc property that has no :class:`Axiom`
follows the same steps, except the record is a plain regression test in
the module's ``test/`` file.

Recording counterexamples
-------------------------

``proptest/test_counterexamples.py`` holds the records and their replay.
A record is structured data: the bound axiom itself and the very
arguments the search shrunk the failure to.

.. code-block:: python

    COUNTEREXAMPLES = (
        Counterexample(
            axiom=Matrix[int].copy_cocommutativity,
            args=(2, ),
            reason="Matrix.copy(x, n) is wrong for x, n >= 2 (#606)"),
        ...)

- ``axiom`` is the class attribute access, which binds the
  :class:`Axiom` to its category — the same object the matrix checks, so
  a record can never drift from the law it witnesses.
- ``args`` are the generated arguments, one per sample, in sampling order —
  actual terms, not strings. Transparency is what lets the falsifying
  samples be pasted verbatim; their reprs are module-qualified, so extend
  the file's imports as records arrive.
- ``reason`` says what broke and links the issue when there is one.

The replay test marks a record xfail, strictly, exactly when its axiom
is declared :meth:`Axiom.failing`, and checks that the arguments falsify
the law: the equation is false or the implementation refuses to build
its terms. A fixed bug shows up as an unexpected pass, which strictness
turns red, and a record never needs updating when the bug is fixed: only
the ``.failing`` declaration moves.

Never delete a record because it is inconvenient; a record only leaves
when the law itself leaves the codebase.

Auditing a strategy that missed a bug
-------------------------------------

A bug found outside the matrix — by hand, by a user, in the wild — while
its law sat green is a coverage escape. The record pins the instance; the
audit closes the class. Check three causes, in order:

1. **Reach.** Can the strategy build the counterexample's shape at all?
   Ask :func:`hypothesis.find` with the category's strategy and a
   predicate for the shape — the structural box involved, the boundary,
   the depth. :class:`hypothesis.errors.NoSuchExample` convicts the
   strategy: declare the missing rule or generator.
2. **Rarity.** Reachable but starved: run the cell with
   ``--hypothesis-show-statistics``, tagging the shape with
   :func:`hypothesis.event` if need be, to see how often it is sampled, and
   check with ``coverage run -m pytest proptest/`` that the buggy lines
   are hit at all. A shape sampled much less than once per ``max_examples``
   is invisible at the matrix's budget: rebalance the strategy's weights
   or grow its size bounds rather than raising the budget.
3. **Observation.** Sampled but not seen: the law compares its equation
   :meth:`Axiom.modulo` a quotient that erases the difference, states
   something weaker than what the bug violates, or the violated law was
   never stated — in which case the fix is a new axiom, stated first as
   in the feature protocol.

The audit is done when the search rediscovers the bug by itself: hold the
fix back and watch the cell go red without help. Only then does the suite
guard the class of bugs and not just the recorded instance.

Continuous integration
----------------------

The ``proptest`` workflow runs the suite on pull requests labelled
``proptest``, on every push to ``main``, nightly, and on manual dispatch.
``proptest/conftest.py`` registers the Hypothesis profiles, selected by
``HYPOTHESIS_PROFILE``, over one example database,
``.hypothesis/examples``:

- ``pr``, on pull requests: a small budget of new examples after the
  ``reuse`` phase has replayed every failure the database remembers, so a
  known bug fails at once and a run is fast. The workflow fixes the seed
  with ``--hypothesis-seed``, which keeps the database where
  ``derandomize`` would drop it, so a pull request samples the same
  examples every time: it is red for its own diff or for a failure the
  artifact already holds, never for luck.
- ``explore``, on ``main``, nightly and on dispatch: a large budget,
  where new counterexamples come from.
- ``dev``, the default elsewhere: a middling budget over the local
  database alone.
- ``fast``, the ``dev`` budget on one cell per declaration of a law: the
  category nearest the class declaring it, rather than every category
  inheriting it. It is the profile to develop with.
- ``shared``, on request: the ``dev`` budget with the local database
  backed by CI's, read-only, through a ``GITHUB_TOKEN``, so what CI found
  replays on your machine. It reaches GitHub only when asked for, never
  as a side effect of a token in the environment.

Every run downloads the database the previous run uploaded as the
``hypothesis-example-db`` artifact; a run of ``main``, the nightly search
or a dispatch uploads its own afterwards — a pull request only reads it —
so a failure found by one night's search fails every pull request until
it is fixed or declared, with no one recording anything.

Explore runs are randomised, so a red check on ``main`` or overnight is
where a new bug surfaces: the shrunk samples in the log and the printed
``@reproduce_failure(<version>, <blob>)`` decorator reproduce it under
the Hypothesis ``uv.lock`` pins, and the artifact replays it on every
pull request and, through the ``shared`` profile, on your machine.
"""


import inspect
import pickle
import sys
from abc import ABCMeta
from collections.abc import Callable, Mapping
from copy import deepcopy
from dataclasses import KW_ONLY, dataclass, field, replace
from functools import wraps
from typing import TYPE_CHECKING, Self

from discopy.pattern import (  # noqa: F401  pylint: disable=unused-import
    Atom, Count, D, Hom, L, Obj, Over, R, Repeat, Tensor, Under, Unit)
from discopy.sequent import (  # noqa: F401  pylint: disable=unused-import
    Declaration, declarations, Sort)
from discopy.search import (  # noqa: F401  pylint: disable=unused-import
    Constant,
    Rule,
    rule,
    search,
)
from discopy.utils import (
    AxiomError,
    NamedGeneric,
    classproperty,
    factory_name,
)

if TYPE_CHECKING:
    from hypothesis import strategies as st


GENERATORS = tuple("abcde")
"""
The names the generators of a free category are sampled from.

They are finitely many and shared, so a generated functor can name every one
of them: composing two functors keeps only the keys of the left-hand map, so
a functor that named just a few would compose to one defined nowhere else.
"""


class Equation[ar](NamedGeneric):
    """
    An equation is a list of ``terms`` to be compared up to a function
    ``up_to``, the identity by default.  Casting it to ``bool`` checks
    whether its terms are all equal up to that function.

    Parameters:
        terms : The terms of the equation.
        symbol : The symbol between each pair of terms, ``"="`` by default.
        symbols : The symbols between each pair of consecutive terms, one
            fewer than the terms, overriding ``symbol``.
        up_to : The function up to which ``bool(equation)`` compares its
            terms, overriding the subclass' :attr:`up_to` if given.

    Example
    -------
    The number of boxes inside an arrow is left unchanged by associativity,
    so we can compare arrows up to the function that counts them modulo 2:

    >>> from discopy.cat import Ob, Box, Equation
    >>> x = Ob('x')
    >>> f, g = Box('f', x, x), Box('g', x, x)
    >>> parity = lambda term: len(term.inside) % 2
    >>> assert not Equation(f, f >> g >> g)
    >>> assert Equation(f, f >> g >> g, up_to=parity)
    """
    up_to = None

    def __init__(self, *terms, symbol="=", symbols=None, up_to=None):
        self.terms = terms
        gaps = max(len(terms) - 1, 0)
        self.symbols = gaps * (symbol, ) if symbols is None\
            else tuple(symbols)
        if len(self.symbols) != gaps:
            raise ValueError(
                f"Expected {gaps} symbols between {len(terms)} terms, "
                f"got {len(self.symbols)}.")
        if up_to is not None:
            self.up_to = up_to

    def modulo(self, up_to: Callable) -> Equation:
        """
        The same equation compared up to the given function, rebinding
        :attr:`up_to`, whose name the attribute already takes.

        >>> from discopy.cat import Ob, Box, Equation
        >>> x = Ob('x')
        >>> f, g = Box('f', x, x), Box('g', x, x)
        >>> assert Equation(f >> g, g >> f).modulo(lambda _: True)
        """
        return type(self)(*self.terms, symbols=self.symbols, up_to=up_to)

    def __repr__(self):
        """
        >>> from discopy.cat import Ob, Box, Equation
        >>> Equation(Box('f', Ob('x'), Ob('x')))
        cat.Equation(cat.Box('f', cat.Ob('x'), cat.Ob('x')))
        """
        return factory_name(type(self))\
            + f"({', '.join(map(repr, self.terms))})"

    def __str__(self):
        return f"Equation({', '.join(map(str, self.terms))})"

    def __bool__(self):
        terms = self.terms if self.up_to is None\
            else list(map(self.up_to, self.terms))
        return all(term == terms[0] for term in terms)

    def checked(self) -> Equation:
        """
        The same equation with ``≠`` between two consecutive terms that
        differ up to :attr:`up_to`, i.e. the inequation it is when it fails.

        >>> from discopy.cat import Ob, Box, Equation
        >>> x = Ob('x')
        >>> f, g = Box('f', x, x), Box('g', x, x)
        >>> Equation(f, f, g).checked().symbols
        ('=', '$\\\\neq$')
        """
        symbols = (
            symbol if type(self)(left, right, up_to=self.up_to)
            else "$\\neq$" for symbol, left, right
            in zip(self.symbols, self.terms, self.terms[1:]))
        return type(self)(*self.terms, symbols=symbols, up_to=self.up_to)


class AxiomFailure(AxiomError):
    """
    A law declared broken, raised when the bound axiom is called: the
    reason is the message and :attr:`equation` is the law evaluated on the
    arguments, whose sides say how it failed.
    """

    def __init__(self, reason: str, equation):
        super().__init__(reason, equation)
        self.equation = equation


class Testable[T](metaclass=ABCMeta):
    """
    A testable class states axioms, which its subclasses inherit along
    with the structure they axiomatise, and says how to generate the
    terms those axioms quantify over.

    Both kinds of law meet here: a :class:`discopy.abc.Category` states
    those of a categorical structure, a :class:`Serialisable` those of
    writing a term down and reading it back. A class need not be a
    category to state laws, which is why the two meet here rather than in
    either of them.

    A type that implements :meth:`strategy` is one the property matrix
    in ``proptest/`` quantifies over, checking each of its axioms against
    generated terms. One that does not is not checked, and says so by
    leaving :meth:`strategy` to raise.
    """

    @classmethod
    def strategy(cls, **params) -> "st.SearchStrategy[T]":
        """
        Build a `search strategy
        <https://hypothesis.readthedocs.io/en/latest/data.html>`_ for
        instances of ``cls``, which is how a class enrols itself in the
        property matrix.

        An override that delegates to another strategy accepts
        ``**params``, pops the parameters it consumes and forwards the
        rest, so that a caller's bounds pass through unchanged and a
        subclass overrides what a base popped just by passing it. A
        terminal strategy instead declares exactly the parameters it
        implements: a constraint it cannot honour fails loudly as an
        unexpected keyword rather than being silently dropped.

        The default raises: a class states its laws as soon as it has
        them, and is checked against them once it says how to sample their
        terms. It is deliberately not an :func:`abc.abstractmethod`,
        which would make every category that has not implemented one
        uninstantiable rather than merely unchecked.

        >>> from discopy.monoidal import Layer
        >>> Layer.strategy()
        Traceback (most recent call last):
         ...
        NotImplementedError: No search strategy implemented for Layer
        """
        raise NotImplementedError(
            f"No search strategy implemented for {cls.__name__}")

    @classproperty
    def axioms(cls: type) -> dict[str, Axiom]:
        """
        The axioms inherited by ``cls``, by name, subclasses overriding
        bases: assigning anything that is not an axiom over an inherited
        one drops it altogether, rather than restating it.
        """
        return declarations(cls, Axiom)

    @classmethod
    def environment(cls) -> dict:
        """
        The namespace the representation of a term reads back in: the
        public names of the package, as ``from discopy import *`` binds
        them, so that a representation qualified by module such as
        ``cat.Box('f', cat.Ob('x'), cat.Ob('y'))`` evaluates, and then
        those of the module the class is defined in, so that one
        printing bare names such as ``Tensor[int]([0], dom=Dim(1),
        cod=Dim(1))`` evaluates too. The module comes second because a
        term prints the names its own module binds: ``Dim`` in
        ``discopy.tensor`` is the one a tensor is built from.

        The import is local because the package imports this module.
        """
        import discopy

        public = lambda namespace: {
            name: value for name, value in namespace.items()
            if not name.startswith("_")}
        module = sys.modules[cls.__module__]
        return dict(public(vars(discopy)), **public(vars(module)))

    @classmethod
    def subclasses(cls) -> tuple[type[Testable], ...]:
        """
        Every transitive subclass of ``cls``, ``cls`` itself included.

        A subclass is listed once, however many paths reach it, in the
        order a breadth-first walk of the subclass graph first meets
        it.

        Example
        -------
        >>> from discopy.cat import Arrow, Box
        >>> assert Arrow.subclasses()[0] is Arrow
        >>> assert Box in Arrow.subclasses()  # a subclass of a subclass
        """
        found, queue = {cls: None}, [cls]
        while queue:
            for subclass in queue.pop(0).__subclasses__():
                if subclass not in found:
                    found[subclass] = None
                    queue.append(subclass)
        return tuple(found)


no_strategy = Testable.__dict__["strategy"]
"""
The default :meth:`Testable.strategy`, under a name that can be assigned.

A class inherits it from :class:`Testable` unless a base it refines
implements one: the terms of a :class:`discopy.monoidal.Ty` are not
those of the :class:`discopy.cat.Ob` it subclasses, so a class that
would inherit the wrong strategy declares ``strategy = no_strategy``
until it implements its own.
"""


@dataclass(repr=False)
class Axiom[**P, T](Declaration[P, T]):
    """
    An axiom of a category: a :class:`discopy.sequent.Declaration` with no
    conclusion, whose premises are the arguments of a property test. The
    axiom is a classmethod of the category it is bound to, implicitly:
    its first parameter is the category and the remaining ones are
    generated from their patterns.

    Calling a bound axiom returns its verdict: :obj:`NotImplemented` when
    the structure does not apply to the category, the equation itself
    otherwise; a law declared broken raises an :class:`AxiomFailure`
    carrying that equation instead. A law is broken when *some* argument
    is a counterexample, so :attr:`broken` is declared by :meth:`failing`
    before any argument is generated: the property matrix marks such a
    law as an expected failure and lets the search find the counterexample.

    Parameters:
        function : The function stating the law, from the category and the
            generated arguments to an :class:`Equation`, or to
            :obj:`NotImplemented` when the structure does not apply.
        params : The parameters :meth:`weaken` passes to the strategy of
            every hom premise, restricting the law to a subspace.
        broken : Whether the law is declared broken by :meth:`failing`.
    """

    _: KW_ONLY
    params: dict = field(default_factory=dict)
    broken: bool = False

    concludes = False

    __hash__ = Declaration.__hash__

    def __get__(self, instance, owner: type) -> Self:
        declaring = next((
            base for base in owner.__mro__
            if base.__dict__.get(self.name or "") is self), None)
        return self.bind(owner, owner=declaring)

    def modulo(self, up_to) -> Self:
        """
        The same law with its equation compared up to a function, so that a
        category weakens an inherited axiom in one statement, e.g. a diagram
        compares the interchange law up to its normal form:
        ``Diagram.bifunctoriality = MonoidalCategory.bifunctoriality.modulo(
        Diagram.normal_form)``.
        """
        @wraps(self.function)
        def equation(*args, **kwargs):
            return self.function(*args, **kwargs).modulo(up_to)
        return replace(self, function=equation)

    def failing(self, reason: str) -> Self:
        """
        The same law declared broken: calling it raises an
        :class:`AxiomFailure` with the reason as message and the equation
        evaluated on the arguments, e.g. ``braid_naturality =
        BraidedCategory.braid_naturality.failing("A free braid is a box.")``.
        """
        @wraps(self.function)
        def equation(*args, **kwargs):
            raise AxiomFailure(reason, self.function(*args, **kwargs))
        equation.__doc__ = reason
        return replace(self, function=equation, broken=True)

    def inapplicable(self, reason: str) -> Self:
        """
        The same law declared not to apply to the category: it takes no
        argument and returns :obj:`NotImplemented`, with the reason as its
        documentation, e.g. ``trace_vanishing =
        TracedCategory.trace_vanishing.inapplicable("No trace.")``.
        """
        def law(cls):
            # pylint: disable=unused-argument  # a law that does not apply
            return NotImplemented
        law.__doc__ = reason
        return replace(self, function=law, params={}, broken=False)

    def weaken(self, **params) -> Self:
        """
        The same law quantified over the subspace the given parameters cut
        out of the strategy of each hom premise, e.g.
        ``bifunctoriality.weaken(boundary_connected=True)`` on a diagram
        category compares the interchange law on the diagrams its normal
        form is defined for. Assigned to its own attribute beside a
        ``.failing`` declaration, it shows the matrix one expected failure
        and one green cell instead of one blanket expected failure.
        """
        return replace(self, params=dict(self.params, **params))

    @property
    def parameters(self) -> tuple[inspect.Parameter, ...]:
        """
        The parameters whose arguments the property matrix generates: all
        but the first, which is the category.
        """
        return tuple(
            inspect.signature(self.function).parameters.values())[1:]

    def equations(self, evaluate: Callable,
                  **params) -> "st.SearchStrategy":
        """
        The law evaluated by a function of its arguments, sampled from their
        patterns; keyword arguments are passed to the strategy of each hom
        premise, after those :meth:`weaken` declared. A law weakened to
        the boundary-connected subspace also keeps its equations there: a
        state and an effect are each boundary-connected while composing
        into a closed component, on which the normal form of a term of
        the equation would not be defined.
        """
        from hypothesis import strategies as st

        if self.category is None:
            raise TypeError(f"{self.name} is not bound to a class.")
        params = dict(self.params, **params)

        def hom(category, dom, cod):
            return category.strategy(dom=dom, cod=cod, **params)

        @st.composite
        def arguments(draw):
            return evaluate(**self.generate(draw, hom)[1])

        if not params.get("boundary_connected"):
            return arguments()
        return arguments().filter(lambda equation: all(
            term.is_boundary_connected for term in equation.terms))

    def strategy(self, **params) -> "st.SearchStrategy[Equation]":
        """
        Generate the equations the bound axiom states: a law declared
        broken raises its :class:`AxiomFailure` from the sample, as it does
        from a call. Keyword arguments are those of :meth:`equations`.

        >>> from hypothesis import find
        >>> from discopy.cat import Arrow
        >>> equation = find(Arrow.unitality.strategy(), lambda _: True)
        >>> assert equation and len(equation.terms) == 3
        """
        return self.equations(self, **params)

    def falsify(self, **params) -> Equation:
        """
        Search for a shrunk counterexample to the bound axiom, a false
        equation of the law, raising :class:`hypothesis.errors.NoSuchExample`
        when none is found. Keyword arguments are passed to
        :func:`hypothesis.find`.

        >>> from hypothesis import settings
        >>> from discopy.cat import Arrow
        >>> Arrow.associativity.falsify(
        ...     settings=settings(max_examples=10))  # doctest: +ELLIPSIS
        Traceback (most recent call last):
         ...
        hypothesis.errors.NoSuchExample: No examples found of condition ...
        """
        from hypothesis import find

        def verdict(**arguments):
            try:
                return self(**arguments)
            except AxiomFailure as failure:
                return failure.equation

        return find(
            self.equations(verdict),
            lambda equation: equation is not NotImplemented
            and not equation, **params)

    def canonical(self) -> Equation:
        """
        The law as a schema: its equation on the canonical arguments of its
        sequent, a box per premise between objects named after the
        variables, the equation a law declared broken raises included.

        >>> from discopy.cat import Arrow
        >>> print(Arrow.associativity.canonical())
        Equation(f >> g >> h, f >> g >> h)
        """
        try:
            return self(**super().canonical())
        except AxiomFailure as failure:
            return failure.equation

    def draw(self, **params):
        """
        Draw the :meth:`canonical` equation of the law, the parameters those
        of :meth:`discopy.monoidal.Equation.draw`. A law the category breaks
        on its canonical instance is drawn all the same, as the inequation it
        is there, see :meth:`Equation.checked`.

        >>> from discopy import braided
        >>> braided.Diagram.braid_naturality.draw(
        ...     doctest="docs/_static/braided/braid-naturality-failing.svg")

        .. image:: /_static/braided/braid-naturality-failing.svg
            :align: center
        """
        equation = self.canonical()
        if equation is NotImplemented:
            raise TypeError(f"{self} does not apply, so has nothing to draw.")
        return equation.checked().draw(**params)

    def arguments(self, /, *args: P.args, **kwargs: P.kwargs) -> dict:
        """ Bind the arguments to the :attr:`parameters` of the axiom. """
        if self.category is None:
            raise TypeError(f"{self.name} is not bound to a class.")
        bound = inspect.Signature(self.parameters).bind(*args, **kwargs)
        bound.apply_defaults()
        return dict(bound.arguments)

    def __call__(self, /, *args: P.args, **kwargs: P.kwargs):
        return self.function(self.category, **self.arguments(*args, **kwargs))


def axiom[**P, T](function: Callable[P, T]) -> Axiom[P, T]:
    """
    Decorate an equation as a categorical axiom: a classmethod of its
    category, implicitly, whose remaining parameters are generated.
    """
    return Axiom(function)


@dataclass(frozen=True, eq=False)
class Relabelling(Mapping):
    """
    A map on the generators of a free category, sending the atoms it names to
    a chosen object, every other atom to itself, and a box to one of the
    same name on the relabelled boundary.

    It is a :class:`Mapping` rather than a closure so that functors built
    from it can be composed and compared, which is what makes the axioms of
    ``Cat`` itself checkable: :meth:`discopy.utils.MappingOrCallable.then`
    composes by iterating the keys of the left-hand map, and equality
    compares the wrapped maps. Iterating yields only the atoms it renames,
    while looking up is total, so a functor built from it as both its
    object and its arrow map applies to any diagram and still composes to
    something comparable.
    """
    images: tuple[tuple[object, object], ...] = ()

    def __repr__(self):
        return factory_name(type(self)) + f"(images={self.images!r})"

    def __getitem__(self, key):
        """
        The image of an atom, looked up by name, or of a box, relabelled on
        its boundary by the functor of the box's own category: a rotation or
        a delay of an atom is that functor's business, e.g.
        :class:`discopy.rigid.Functor`'s, on a box's boundary as on an
        object.

        The import is local because :mod:`discopy.cat` imports this module
        for its strategies, so the arrow between them cannot be reversed.
        """
        from discopy.cat import Functor, Ob

        if not isinstance(key, Ob):
            functor = getattr(type(key), "Functor", Functor)
            relabel = functor(self, self)
            return type(key)(key.name, relabel(key.dom), relabel(key.cod))
        wire, = getattr(key, "inside", (key, ))
        for atom, image in self.images:
            other, = getattr(atom, "inside", (atom, ))
            if other.name == wire.name:
                return image
        return key

    def __iter__(self):
        return iter([atom for atom, _ in self.images])

    def __len__(self):
        return len(self.images)

    def __bool__(self):
        """ A relabelling is total, even when it renames nothing. """
        return True


def assert_axioms(*categories) -> None:
    """
    Check every axiom of each category on a single generated equation, a
    dry run of the property tests in ``proptest/``.

    An axiom that does not apply is skipped, a broken one is only required
    to raise its :class:`discopy.utils.AxiomError` — one example need not
    be a counterexample — and any other law must hold.
    """
    from hypothesis import Phase, find, settings

    single_shot = settings(
        max_examples=1, phases=(Phase.generate, ), database=None)
    for category in categories:
        for law in category.axioms.values():
            if not law.parameters and law() is NotImplemented:
                continue
            try:
                equation = find(
                    law.strategy(), lambda value: True, settings=single_shot)
            except AxiomError:
                assert law.broken, law
            else:
                assert equation is NotImplemented or equation, law


class Serialisable(Testable):
    """
    The serialisation interface of DisCoPy, one hook driving all three
    mechanisms: the class attribute ``serialised_attrs`` names attributes that
    are also keyword arguments of ``__init__``, from which follow

    - a generic pair of inverse methods :meth:`to_tree` and
      :meth:`from_tree`, the JSON serialisation behind
      :func:`discopy.utils.dumps` and :func:`discopy.utils.loads`,
    - a generic :meth:`__repr__` such that ``eval(repr(x)) == x``,
    - :meth:`__setstate__` for the pickle protocol; the class
      parameters of :class:`discopy.utils.NamedGeneric` are pickled by
      their own machinery.

    A subclass with a different constructor declares its keys once
    instead of reimplementing each method.

    Each mechanism comes with the law that it is a roundtrip, i.e. that
    a term reads back from what it was written to:
    :meth:`repr_transparency`
    for its representation, :meth:`pickling` and :meth:`copying` for the
    pickle protocol and :meth:`serialisation` for its tree. They are
    axioms like any other, so a class that also implements
    :meth:`discopy.axioms.Testable.strategy` has them checked against
    generated terms, and one that violates a law declares it
    ``.failing`` rather than leaving it untested.

    Example
    -------
    >>> from discopy.cat import Box
    >>> assert Box.serialised_attrs\\
    ...     == ('name', 'dom', 'cod', 'is_dagger', 'data')
    >>> f = Box('f', 'x', 'y', data=42)
    >>> assert Box.from_tree(f.to_tree()) == f
    """
    serialised_attrs: tuple[str, ...] = ()

    def is_default(self, key: str) -> bool:
        """
        Whether the value of an attribute equals its class default,
        in which case :meth:`to_tree` and :meth:`__repr__` drop it.

        Parameters:
            key : The name of the attribute.
        """
        if not hasattr(type(self), key):
            return False
        value, default = getattr(self, key), getattr(type(self), key)
        return value is default or (
            type(value) is type(default) and value == default)

    def __repr__(self):
        """
        The transparent representation of a DisCoPy object: an attribute
        without a class default is positional, one that differs from its
        default is a keyword argument and one equal to it is dropped.

        Example
        -------
        >>> import discopy
        >>> from discopy.cat import Box
        >>> f = Box('f', 'x', 'y', data=42)
        >>> f
        cat.Box('f', cat.Ob('x'), cat.Ob('y'), data=42)
        >>> assert eval(repr(f), vars(discopy)) == f
        """
        return factory_name(type(self)) + "(" + ", ".join(
            f"{key}={repr(getattr(self, key))}" if hasattr(type(self), key)
            else repr(getattr(self, key))
            for key in self.serialised_attrs if not self.is_default(key)) + ")"

    def __setstate__(self, state):
        """
        Restore a pickled state.

        Parameters:
            state : The pickled state of the object.
        """
        self.__dict__.update(state)

    def to_tree(self) -> dict:
        """
        Serialise a DisCoPy object, see :func:`dumps`.

        The tree records the :func:`factory_name` and then each of the
        ``serialised_attrs``, dropping a key when its value equals the
        class attribute of the same name, e.g. a box that is not a
        dagger. An attribute with a ``to_tree`` method is serialised, a
        non-empty list or tuple of such attributes becomes the list of
        their trees, raw JSON data passes through unchanged.

        Example
        -------
        >>> from pprint import PrettyPrinter
        >>> pprint = PrettyPrinter(indent=4, width=70, sort_dicts=False).pprint
        >>> from discopy.cat import Box
        >>> f = Box('f', 'x', 'y', data=42)
        >>> pprint((f >> f[::-1]).to_tree())
        {   'factory': 'cat.Arrow',
            'inside': [   {   'factory': 'cat.Box',
                              'name': 'f',
                              'dom': {'factory': 'cat.Ob', 'name': 'x'},
                              'cod': {'factory': 'cat.Ob', 'name': 'y'},
                              'data': 42},
                          {   'factory': 'cat.Box',
                              'name': 'f',
                              'dom': {'factory': 'cat.Ob', 'name': 'y'},
                              'cod': {'factory': 'cat.Ob', 'name': 'x'},
                              'is_dagger': True,
                              'data': 42}],
            'dom': {'factory': 'cat.Ob', 'name': 'x'},
            'cod': {'factory': 'cat.Ob', 'name': 'x'}}
        """
        tree = {'factory': factory_name(type(self))}
        for key in self.serialised_attrs:
            if self.is_default(key):
                continue
            value = getattr(self, key)
            if hasattr(value, 'to_tree'):
                value = value.to_tree()
            elif isinstance(value, (list, tuple)) and value and all(
                    hasattr(v, 'to_tree') for v in value):
                value = [v.to_tree() for v in value]
            tree[key] = value
        return tree

    @classmethod
    def from_tree(cls, tree: dict) -> Serialisable:
        """
        Decode a serialised DisCoPy object, see :func:`loads`.

        A key missing from the tree falls back to the default value of
        the corresponding keyword argument of ``__init__``. A value with
        a ``'factory'`` key decodes recursively, a non-empty list of
        such values to the tuple of decoded objects, raw JSON data
        passes through unchanged.

        Parameters:
            tree : DisCoPy serialisation.

        Example
        -------
        >>> from discopy.cat import Ob
        >>> assert Ob.from_tree({'factory': 'cat.Ob', 'name': 'x'}) == Ob('x')
        """
        from discopy.utils import from_tree

        kwargs = {}
        for key in cls.serialised_attrs:
            if key not in tree:
                continue
            value = tree[key]
            if isinstance(value, dict) and 'factory' in value:
                value = from_tree(value)
            elif isinstance(value, list) and value and all(
                    isinstance(v, dict) and 'factory' in v for v in value):
                value = tuple(map(from_tree, value))
            kwargs[key] = value
        return cls(**kwargs)

    @axiom
    def repr_transparency(cls, term: Self) -> Equation:
        """
        The representation of a term evaluates back to it, in the
        :meth:`environment` of its type.

        Its ``str`` reads back too, which STYLE.md asks of every term
        under "the obvious variable naming convention", but the
        environment that convention needs is more than a namespace, so
        ``str_transparency`` is left to
        `#764 <https://github.com/discopy/discopy/issues/764>`_.
        """
        return Equation(eval(repr(term), cls.environment()), term)

    @axiom
    def pickling(cls, term: Self) -> Equation:
        """
        A term loads back from its pickle, of the same class: the equation
        is between the pairs of a class and a term, since a subscript of a
        :class:`discopy.utils.NamedGeneric` is part of what a pickle keeps.
        """
        loaded = pickle.loads(pickle.dumps(term))
        return Equation((type(loaded), loaded), (type(term), term))

    @axiom
    def copying(cls, term: Self) -> Equation:
        """
        A term is equal to its deep copy, of the same class. Copying goes
        through the same protocol as :meth:`pickling` without the bytes,
        so a class whose reduction drops what its state needs — the
        parameters of a :class:`discopy.utils.NamedGeneric`, say — breaks
        one law with the other.
        """
        copied = deepcopy(term)
        return Equation((type(copied), copied), (type(term), term))

    @axiom
    def serialisation(cls, term: Self) -> Equation:
        """
        A term decodes back from its tree and from the JSON of its tree.
        A type without a tree declares the law inapplicable.
        """
        from discopy.utils import dumps, from_tree, loads

        return Equation(from_tree(term.to_tree()), loads(dumps(term)), term)
