"""
The search for diagrams by the rules of their category: a :class:`Rule`
is a :class:`discopy.pattern.Declaration` with a conclusion, and
:func:`search` builds a term of a goal type by choosing at each step a
free box, a rule with no hom premise whose conclusion matches the goal —
a generator, built in one step — or, below the depth bound, a
:meth:`Rule.recursive` one whose hom premises are searched.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Rule
    Constant

.. admonition:: Functions

    .. autosummary::
        :template: function.rst
        :nosignatures:
        :toctree:

        rule
        search
"""

from collections.abc import Callable, Iterator
from dataclasses import dataclass, replace
from inspect import signature
from types import MethodType
from typing import Self, TYPE_CHECKING

from discopy.pattern import Declaration, Hom, Match, Sequent

if TYPE_CHECKING:

    pass


class DeadEnd(Exception):
    """ A goal nothing closes within the depth: :func:`search` retries
    it a bounded number of times before rejecting the example. """


@dataclass(repr=False)
class Rule[**P, T](Declaration[P, T]):
    """
    An inference rule of a category, a
    :class:`discopy.pattern.Declaration` with a conclusion: every rule
    states its sequent as its own signature and :func:`search` calls
    the attribute of the same name on the category. Accessed on a
    class, a rule binds to it, once per class; on an instance, it
    behaves as the method it decorates.

    >>> from discopy.abc import Category
    >>> print(Category.then)
    then: A: C0, B: C0, C: C0 | self: C1[A, B], other: C1[B, C] ⊢ C1[A, C]
    """

    __hash__ = Declaration.__hash__

    def __get__(self, instance, owner: type):
        if instance is not None:
            return MethodType(self.function, instance)
        bound = self.__dict__.get("bound")
        if bound is None:
            bound = self.__dict__["bound"] = {}
        if owner not in bound:
            declaring = next((
                base for base in owner.__mro__
                if self.is_declared(base.__dict__.get(self.name or ""))),
                None)
            bound[owner] = self.bind(owner, owner=declaring)
        return bound[owner]

    def is_declared(self, value) -> bool:
        """ Whether a class attribute is this very declaration. """
        value = getattr(value, "__func__", value)
        return value is self

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T:
        return self.function(*args, **kwargs)

    def match(self, dom=None, cod=None) -> Iterator[Match]:
        """ Unify the conclusion with a goal. """
        return self.sequent.conclusion.match((dom, cod))

    @property
    def recursive(self) -> bool:
        """
        Whether a premise is a hom, which the search proves recursively
        below its depth bound; a rule with none is a generator, built in
        one step, see :meth:`discopy.abc.Category.generators`.

        >>> from discopy.abc import Category, RigidCategory
        >>> assert Category.then.recursive
        >>> assert not RigidCategory.cups.recursive
        """
        return any(
            isinstance(premise, Hom)
            for premise in self.sequent.premises.values())

    def apply(self, arguments: dict) -> T:
        """ The implementation of the rule on the category, applied
        positionally in premise order except the keyword-only parameters,
        applied by name. """
        function = getattr(self.category, self.name or "")
        try:
            keywords = {
                name for name, parameter
                in signature(function).parameters.items()
                if parameter.kind == parameter.KEYWORD_ONLY}
        except ValueError:
            keywords = set()
        return function(
            *(x for name, x in arguments.items() if name not in keywords),
            **{name: x for name, x in arguments.items() if name in keywords})

    @staticmethod
    def constant(box) -> Constant:
        """ The rule of one given box, see :class:`Constant`. """
        return Constant(box)

    def inapplicable(self, reason: str) -> Self:
        """
        The same rule dropped from the rules and generators of the
        class it is assigned on, with the reason as its record: the
        method still runs, the search just never applies it, e.g.
        ``trace_left = rule(Diagram.trace_left).inapplicable("No loop
        in a sentence.")``.
        """
        result = replace(self)
        result.__inapplicable__ = reason
        return result


@dataclass(repr=False)
class Constant(Rule):
    """
    The rule of one given box: it applies exactly to the sequent of the
    box and builds it, so that a category generated by a fixed vocabulary
    — the words of a grammar, the gates of a circuit — assigns a
    dictionary of these to its ``generators``.

    >>> from discopy.grammar import pregroup
    >>> n = pregroup.Ty('n')
    >>> rule = Rule.constant(pregroup.Word('Alice', n))
    >>> assert rule.apply({}) == pregroup.Word('Alice', n)
    """

    __hash__ = Declaration.__hash__

    def __post_init__(self):
        self.name = self.name or str(self.function)
        self.__doc__ = f"The constant {self.name}."

    @property
    def sequent(self) -> Sequent:
        return Sequent()

    def match(self, dom=None, cod=None) -> Iterator[Match]:
        box = self.function
        if dom in (None, box.dom) and cod in (None, box.cod):
            yield {}, ()

    def generate(self, draw, hom, subst=None, residuals=(), types=None):
        return dict(subst or {}), {}

    def apply(self, arguments: dict):
        return self.function


def rule[**P, T](function: Callable[P, T]) -> Rule[P, T]:
    """ Decorate a method as an inference rule, its signature the sequent. """
    return Rule(function)
